name: Check stable versions

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # every day
    - cron:  '15 1 * * *'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm i
      - run: npm run stable
        env:
          GITHUB_TOKEN: ${{ secrets.OWN_GITHUB_TOKEN }}
